// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojuihhztvdemtzglkxaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qdWloaHp0dmRlbXR6Z2xreGFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5ODY2OTksImV4cCI6MjA2NjU2MjY5OX0.nYvs3t6ccg1zSIxdzP_4i2nnTytVXbVH-bVunyVLFMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});